# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "glennfaison"
      - run: yarn install
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: yarn version --minor
      - run: git push --tags && git push
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PROVIDER_CALLBACK_HOST: http://test.com
          TARGET_ENVIRONMENT: sandbox
          COLLECTIONS_PRIMARY_KEY: ${{secrets.COLLECTIONS_PRIMARY_KEY}}
          COLLECTIONS_SECONDARY_KEY: ${{secrets.COLLECTIONS_SECONDARY_KEY}}
          DISBURSEMENTS_PRIMARY_KEY: ${{secrets.DISBURSEMENTS_PRIMARY_KEY}}
          DISBURSEMENTS_SECONDARY_KEY: ${{secrets.DISBURSEMENTS_SECONDARY_KEY}}
          REMITTANCES_PRIMARY_KEY: ${{secrets.REMITTANCES_PRIMARY_KEY}}
          REMITTANCES_SECONDARY_KEY: ${{secrets.REMITTANCES_SECONDARY_KEY}}
